apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  annotations:
    github.com/project-slug: enzodjabali/backstage
    backstage.io/techdocs-ref: value
spec:
  type: other
  lifecycle: unknown
  owner: Enzo
